### PR TITLE
Add 'ref' param to auth request

### PR DESCRIPTION
**Pull request by stephenchen13**

### CODE REVIEW

**Comment by michaelherold** [comment]
@stephenchen13 I've looked into this and agree that it should be added. I have made changes since you submitted this PR so it requires a rebase. Are you interested in following up and rebasing, or should I just go ahead and work it in myself?

If you do want to follow up, I'll need you to add a line to the change log, add a test pair that shows it only gets passed when `ref` is non-nil, and write up some information in the readme.

I'm planning on releasing a new version on Saturday so please let me know if you want to follow up before then, otherwise I will move forward with it.

**Comment by stephenchen13** [comment]
Hey @michaelherold,

I'd like to help with this PR but could use some of your guidance. I'm having trouble getting the existing specs to pass locally, the first two specs fail with a ```RuntimeError: missing rack.input```. Do you know what the issue might be?

**Comment by michaelherold** [comment]
Usually that means that there's something wrong with the `env` hash on the Rack response. What spec is throwing the error?

**Comment by michaelherold** [comment]
I went ahead and pulled your commit in 08ddebe, then cleaned it up (cdbdb46) and added readme instructions (8b40910) in some subsequent commits. It will be in the release I'm planning for later today.

**Comment by stephenchen13** [comment]
Thanks, Michael.

**Pull request closed without merging**
